### ISSUE TITLE
Deployment Controller Feature List

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#19]
# Deployment Controller Feature List
This is a list of features to add to the base deployment controller that was made in #16. 
Do not make the changes in one branch, instead create a new issue for each feature, I just put everything in this issue as a list for now.

- [ ] Run the right playbook based off app type
- [x]  Contact someone to get adbuild user space and login for build system to use for deployment. This adbuild user will have to be on all facilities. And this would be needed for SSH access from ephemeral deployment containers.
- [x] Add logic so every facility has their own list of iocs, then confirm with User that the ioc's they want to deploy are in the facilities found
- [x] Consider removing (initial) option for `bs deploy` since the file commands are idempotent

**Comment by pnispero** [comment]
Deployment Cases:

1. For production testing/deployment. We would deploy the candidate test app alongside the real one. Then point the official sym link to the test app just for the production tests. Then if tests are good, then deploy the new official version, and point the sym link to it. If a test fail, revert the link to the last known good tag, delete the test app. 
1a. Create a provisional build that is virtually identical to the official build, then if tests pass, leave in place and rename as the official build, and point the sym link to it. and update the tag in the repo.

**Comment by pnispero** [comment]
**TODO**
1. Maybe jesse knows if we can ssh from k8s pod -> mcc -> prod? Send email. He did have his alarms read production data in to the k8s pod.
2. get end-to-end demo ready by week come back in January. Need one for oscilloscope (mostly done), and one for PYDM.

**Comment by pnispero** [comment]
Use cases:
1. Deploy ALL to facility(s) - `bs deploy --ioc ALL --facility LCLS --tag test-ioc-1.0.0` 
2. Deploy specific iocs - `bs deploy --ioc sioc-demo-1,sioc-demo-2,sioc-demo3 --tag test-ioc-1.0.0`
3. Deploy

**Comment by pnispero** [comment]
## Tagging

### Testing out tagging, and creating a github release (tag + assets)
```
(ana-4.0.65-py3) [pnispero@sdfiana018 oscilloscope]$ git tag -m "Initial test tag R1.0.0" R1.0.0
(ana-4.0.65-py3) [pnispero@sdfiana018 oscilloscope]$ git tag -l
R1.0.0
(ana-4.0.65-py3) [pnispero@sdfiana018 oscilloscope]$ git push origin R1.0.0
```

**Comment by pnispero** [comment]
There is an issue with copy and pasting ssh key
to the vault introduces some errors with unix compatability of the text. So try to see how to add 
the key to the vault using command line instead, that should fix the issue.
Tried it but seems like permissions are limited on the cli compared to the website, will ask s3df admins later.

Since vault not working, just mount the ssh key manually as a secret in kubernetes for now. 
`kubectl -n core-build-system create secret generic deployment-controller-ssh-keys --from-file=s3df-key=/home/pnispero/.ssh/deployme
nt_controller_s3df --from-file=s3df-key-pub=/home/pnispero/.ssh/deployment_controller_s3df.pub
secret/deployment-controller-ssh-keys created`

**Comment by pnispero** [comment]
Performed the demo and everything works for deployment for now. The other features like revert can be done on separate issues. But for now this is a working condition and will merge to main
