### ISSUE TITLE
Build container logic - logging

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#21]
# Build container logic - logging
Update build container scripts so we use logger in python instead of basic print(). This way we can log to console output, and to a text file.
## TODO
- [ ] Logging to both console and to a text file `build_output.txt`
- [ ] Update all `print()` to `logging.info()` in `build_deploy_scripts/`
- [ ] Store the `build.log` as part of the `build_results/`
- [ ] Rebuild latest development images to include these changes
