### ISSUE TITLE
CLI - frontend fixes

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#23]
# CLI - frontend fixes
## TODO
- [x] Pull out the RUN commands (build, test, deployment) up one level at the root level
- [x] Shorten deployment to just deploy, like `bs deploy`
- [x] Make the order of commands make sense
- [x] Make a function for `under construction` for commands not working yet (checkout, and tag)
