### ISSUE TITLE
CLI - Mark ready and not ready

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#31]
# CLI - Mark ready and not ready
## TODO
- [x] CLI command to `bs mark`
- [x] CLI command to `bs mark --clear`
- [ ] Make an Issue on backend to add a field 'status' for the branches, either `ready` or `not ready`
- [ ] And in the backend add a comment on the PR saying marked ready

**Comment by pnispero** [comment]
**remove this comment once you move to appropriate spot**
Patrick - right now work on getting deployment of buildsystem on ad-build (it should be automated with like a command). And try to get the BuildSystem itself through the build system. This way we are closer to getting it to production. 
**Also Lets move all github issues to Jira now. and make a component on Jira.**

**Comment by pnispero** [comment]
Also threw in some fixes to build images - may move this to different issue
