### ISSUE TITLE
CLI - local build should start the correct apptainer environment

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#33]
# CLI - local build should start the correct apptainer environment
## TODO
- [x] Have the local build CLI command start an apptainer based off operating system chosen
- [x] Then will do the same thing as usually but in the apptainer, so parse the `config.yaml`, run the build, then run the playbook to build the package 
- [x] See if Jerry can run the same local build on his end, might error out because I point the playbooks to my BuildSystem directory, maybe can move it to shared `ad-build` so anyone can do it for now, and move any other local filepaths to shared directory. Move the playbooks directory path, the build images directory path to the cli_configuration.py
