### ISSUE TITLE
Build container - Update local build to run unit tests like remote build

### ISSUE THREAD

**Issue by pnispero** [ad-build-test/BuildSystem#34]
# Build container - Update local build
## TODO
- [x] dont forget to add EPICS_HOST_ARCH on the build environment dockerfiles
- [x] Update local_build.py so it can run unit tests just like remote build. 
- [ ] Not part of this issue, but update RELEASE_SITE for oscilloscope to point to /sdf/sw

**Comment by pnispero** [comment]
add a bs deploy --test, and make it under development for now

**Comment by pnispero** [comment]
add the mark command as well

**Comment by pnispero** [comment]
add the test options (quick, and main), and make it under development for now
